[package]
name = "check-git-status"
version = "1.3.1"
edition = "2021"

[[bin]]
name = "check-git-status"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
walkdir = "2.5"
rayon = "1.10"
anyhow = "1.0"
dirs = "5.0"
term_size = "0.3"
